name: Delete Repository

on:
  push:
    branches:
      - main

jobs:
  delete-repo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Delete Repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X DELETE \
          -H "Authorization: token $GITHUB_TOKEN" \
          https://api.github.com/repos/<owner>/<repo>
